name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  commit_comment:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: test sequential code
      run: ./c_version/sequential_version/sequential_deploy.c 30 10 1 0.4 0.5
    - name: test parallel code
      run: ./c_version/parallel_version/parallel_deploy.c 30 10 1 0.4 0.5 4
    - name: make check
      run: make check
