name: C/C++ CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: test
      run: ./c_version/sequential_deploy.exe 30 10 1 0.4 0.5

